export const URL_IMAGENES = 'http://localhost:3000/imagen';
export const URL_PRODUCTOS = 'http://localhost:3000/producto';
export const URL_CATEGORIA = 'http://localhost:3000/categoria';
export const URL_ENTORNO = 'http://localhost:3000/entorno';
export const URL_PEDIDO = 'http://localhost:3000/pedido';
export const URL_USUARIOS = 'http://localhost:3000/users';
export const URL_SERVICE_ID= 'http://localhost:3000/email/serviceId';
export const URL_TEMPLATE_ID= 'http://localhost:3000/email/templateId';
export const URL_USER_ID= 'http://localhost:3000/email/userId';